
lady = Category.create(:genre=>"レディース")
men = Category.create(:genre=>"メンズ")
kids = Category.create(:genre=>"ベビー・キッズ")
houseware = Category.create(:genre=>"インテリア・住まい・小物")
entertainment = Category.create(:genre=>"本・音楽・ゲーム")
hobby = Category.create(:genre=>"おもちゃ・ホビー・グッズ")
cosme = Category.create(:genre=>"コスメ・香水・美容")
electric = Category.create(:genre=>"家電・スマホ・カメラ")
sports = Category.create(:genre=>"スポーツ・レジャー")
handmade = Category.create(:genre=>"ハンドメイド")
ticket = Category.create(:genre=>"チケット")
behicle = Category.create(:genre=>"自動車・オートバイ")
others = Category.create(:genre=>"その他")

lady_tops = lady.children.create(:genre=>"トップス")
lady_jacket = lady.children.create(:genre=>"ジャケット/アウター")
lady_pants = lady.children.create(:genre=>"パンツ")
lady_skirt = lady.children.create(:genre=>"スカート")
lady_onepiece = lady.children.create(:genre=>"ワンピース")
lady_shoes = lady.children.create(:genre=>"靴")
lady_pajama = lady.children.create(:genre=>"ルームウェア/パジャマ")
lady_legwear = lady.children.create(:genre=>"レッグウェア")
lady_hat = lady.children.create(:genre=>"帽子")
lady_bag = lady.children.create(:genre=>"バッグ")
lady_accessory = lady.children.create(:genre=>"アクセサリー")
lady_hairacc = lady.children.create(:genre=>"ヘアアクセサリー")
lady_small = lady.children.create(:genre=>"小物")
lady_watch = lady.children.create(:genre=>"時計")
lady_wig = lady.children.create(:genre=>"ウィッグ/エクステ")
lady_yukata = lady.children.create(:genre=>"浴衣/水着")
lady_suits = lady.children.create(:genre=>"スーツ/フォーマル/ドレス")
lady_maternity = lady.children.create(:genre=>"マタニティ")
lady_others = lady.children.create(:genre=>"その他")
men_tops = men.children.create(:genre=>"トップス")
men_jacket = men.children.create(:genre=>"ジャケット/アウター")
men_pants = men.children.create(:genre=>"パンツ")
men_shoes = men.children.create(:genre=>"靴")
men_bag = men.children.create(:genre=>"バッグ")
men_suits = men.children.create(:genre=>"スーツ")
men_hat = men.children.create(:genre=>"帽子")
men_accessory = men.children.create(:genre=>"アクセサリー")
men_small = men.children.create(:genre=>"小物")
men_watch = men.children.create(:genre=>"時計")
men_swimsuits = men.children.create(:genre=>"水着")
men_legwear = men.children.create(:genre=>"レッグウェア")
men_underwear = men.children.create(:genre=>"アンダーウェア")
men_others = men.children.create(:genre=>"その他")
kids_baby_girl = kids.children.create(:genre=>"ベビー服(女の子用)~95cm")
kids_baby_boy = kids.children.create(:genre=>"ベビー服(男の子用)~95cm")
kids_baby_uni = kids.children.create(:genre=>"ベビー服(男女兼用)~95cm")
kids_girl = kids.children.create(:genre=>"キッズ服(女の子用) 100cm~")
kids_boy = kids.children.create(:genre=>"キッズ服(男の子用) 100cm~")
kids_uni = kids.children.create(:genre=>"キッズ服(男女兼用) 100cm~")
kids_wear = kids.children.create(:genre=>"キッズ靴")
kids_small = kids.children.create(:genre=>"子ども用ファッション小物")
kids_bath = kids.children.create(:genre=>"おむつ/トイレ/バス")
kids_outside = kids.children.create(:genre=>"外出/移動用品")
kids_meal = kids.children.create(:genre=>"授乳/食事")
kids_bed = kids.children.create(:genre=>"ベビー家具/寝具/室内用品")
kids_toy = kids.children.create(:genre=>"おもちゃ")
kids_anni = kids.children.create(:genre=>"行事/記念品")
kids_others = kids.children.create(:genre=>"その他")
houseware_kitchen = houseware.children.create(:genre=>"キッチン/食器")
houseware_bed = houseware.children.create(:genre=>"ベッド/マットレス")
houseware_sofa = houseware.children.create(:genre=>"ソファ/ソファベッド")
houseware_chair = houseware.children.create(:genre=>"椅子/チェア")
houseware_table = houseware.children.create(:genre=>"机/テーブル")
houseware_storage = houseware.children.create(:genre=>"収納家具")
houseware_carpet = houseware.children.create(:genre=>"ラグ/カーペット/マット")
houseware_curtain = houseware.children.create(:genre=>"カーテン/ブラインド")
houseware_light = houseware.children.create(:genre=>"ライト/照明")
houseware_bedding = houseware.children.create(:genre=>"寝具")
houseware_interior = houseware.children.create(:genre=>"インテリア小物")
houseware_seasonal = houseware.children.create(:genre=>"季節/年中行事")
houseware_others = houseware.children.create(:genre=>"その他")
entertainment_book = entertainment.children.create(:genre=>"本")
entertainment_comic = entertainment.children.create(:genre=>"漫画")
entertainment_magazine = entertainment.children.create(:genre=>"雑誌")
entertainment_cd = entertainment.children.create(:genre=>"CD")
entertainment_dvd = entertainment.children.create(:genre=>"DVD/ブルーレイ")
entertainment_record = entertainment.children.create(:genre=>"レコード")
entertainment_game = entertainment.children.create(:genre=>"テレビゲーム")
hobby_toy = hobby.children.create(:genre=>"おもちゃ")
hobby_talent = hobby.children.create(:genre=>"タレントグッズ")
hobby_comic_goods = hobby.children.create(:genre=>"コミック/アニメグッズ")
hobby_cards = hobby.children.create(:genre=>"トレーディングカード")
hobby_figure = hobby.children.create(:genre=>"フィギュア")
hobby_instrument = hobby.children.create(:genre=>"楽器/器材")
hobby_collection = hobby.children.create(:genre=>"コレクション")
hobby_military = hobby.children.create(:genre=>"ミリタリー")
hobby_picture = hobby.children.create(:genre=>"美術品")
hobby_art = hobby.children.create(:genre=>"アート用品")
hobby_others = hobby.children.create(:genre=>"その他")
cosme_base = cosme.children.create(:genre=>"ベースメイク")
cosme_makeup = cosme.children.create(:genre=>"メイクアップ")
cosme_nail = cosme.children.create(:genre=>"ネイルケア")
cosme_perfume = cosme.children.create(:genre=>"香水")
cosme_skincare = cosme.children.create(:genre=>"スキンケア/基礎化粧品")
cosme_haircare = cosme.children.create(:genre=>"ヘアケア")
cosme_bodycare = cosme.children.create(:genre=>"ボディケア")
cosme_oralcare = cosme.children.create(:genre=>"オーラルケア")
cosme_relax = cosme.children.create(:genre=>"リラクゼーション")
cosme_diet = cosme.children.create(:genre=>"ダイエット")
cosme_others = cosme.children.create(:genre=>"その他")
electric_phone = electric.children.create(:genre=>"スマートフォン/携帯電話")
electric_accessory = electric.children.create(:genre=>"スマホアクセサリー")
electric_pc = electric.children.create(:genre=>"PC/タブレット")
electric_camera = electric.children.create(:genre=>"カメラ")
electric_tv = electric.children.create(:genre=>"テレビ/映像機器")
electric_audio = electric.children.create(:genre=>"オーディオ機器")
electric_beauty = electric.children.create(:genre=>"美容/健康")
electric_aircon = electric.children.create(:genre=>"冷暖房/空調")
electric_appliance = electric.children.create(:genre=>"生活家電")
electric_others = electric.children.create(:genre=>"その他")
sports_golf = sports.children.create(:genre=>"ゴルフ")
sports_fishing = sports.children.create(:genre=>"フィッシング")
sports_bike = sports.children.create(:genre=>"自転車")
sports_exercise = sports.children.create(:genre=>"トレーニング/エクササイズ")
sports_baseball = sports.children.create(:genre=>"野球")
sports_soccer = sports.children.create(:genre=>"サッカー/フットサル")
sports_tennis = sports.children.create(:genre=>"テニス")
sports_snowboard = sports.children.create(:genre=>"スノーボード")
sports_ski = sports.children.create(:genre=>"スキー")
sports_other_sports = sports.children.create(:genre=>"その他スポーツ")
sports_outdoor = sports.children.create(:genre=>"アウトドア")
sports_others = sports.children.create(:genre=>"その他")
handmade_accessory = handmade.children.create(:genre=>"アクセサリー(女性用)")
handmade_small = handmade.children.create(:genre=>"ファッション/小物")
handmade_watch = handmade.children.create(:genre=>"アクセサリー/時計")
handmade_interior = handmade.children.create(:genre=>"日用品/インテリア")
handmade_hobby = handmade.children.create(:genre=>"趣味/おもちゃ")
handmade_kids = handmade.children.create(:genre=>"キッズ/ベビー")
handmade_material = handmade.children.create(:genre=>"素材/材料")
handmade_fanmade = handmade.children.create(:genre=>"二次創作物")
handmade_others = handmade.children.create(:genre=>"その他")
ticket_music = ticket.children.create(:genre=>"音楽")
ticket_sports = ticket.children.create(:genre=>"スポーツ")
ticket_entertainment = ticket.children.create(:genre=>"演劇/芸能")
ticket_event = ticket.children.create(:genre=>"イベント")
ticket_movie = ticket.children.create(:genre=>"映画")
ticket_facility = ticket.children.create(:genre=>"施設利用券")
ticket_voucher = ticket.children.create(:genre=>"優待券/割引券")
ticket_otehrs = ticket.children.create(:genre=>"その他")
behicle_car = behicle.children.create(:genre=>"自動車本体")
behicle_wheel = behicle.children.create(:genre=>"自動車タイヤ/ホイール")
behicle_part = behicle.children.create(:genre=>"自動車パーツ")
behicle_accessory = behicle.children.create(:genre=>"自動車アクセサリー")
behicle_autobike = behicle.children.create(:genre=>"オートバイ車体")
behicle_bike_part = behicle.children.create(:genre=>"オートバイパーツ")
behicle_bike_accessory = behicle.children.create(:genre=>"オートバイアクセサリー")
others_bigshop = others.children.create(:genre=>"まとめ売り")
others_pet = others.children.create(:genre=>"ペット用品")
others_food = others.children.create(:genre=>"食品")
others_bevarage = others.children.create(:genre=>"飲料/酒")
others_grocery = others.children.create(:genre=>"日用品/生活雑貨/旅行")
others_antique = others.children.create(:genre=>"アンティーク/コレクション")
others_stationary = others.children.create(:genre=>"文房具/事務用品")
others_shop = others.children.create(:genre=>"事務/店舗用品")
others_others = others.children.create(:genre=>"その他")

lady_tops.children.create([{:genre=>"Tシャツ/カットソー(半袖/袖なし)"},{:genre=>"Tシャツ/カットソー(七分/長袖)"},{:genre=>"シャツ/ブラウス(半袖/袖なし)"},{:genre=>"シャツ/ブラウス(七分/長袖)"},{:genre=>"ポロシャツ"},{:genre=>"キャミソール"},{:genre=>"タンクトップ"},{:genre=>"ホルターネック"},{:genre=>"ニット/セーター"},{:genre=>"チュニック"},{:genre=>"カーディガン/ボレロ"},{:genre=>"アンサンブル"},{:genre=>"ベスト/ジレ"},{:genre=>"パーカー"},{:genre=>"トレーナー/スウェット"},{:genre=>"ベアトップ/チューブトップ"},{:genre=>"ジャージ"},{:genre=>"その他"}])
lady_jacket.children.create([{:genre=>"テーラードジャケット"},{:genre=>"ノーカラージャケット"},{:genre=>"Gジャン/デニムジャケット"},{:genre=>"レザージャケット"},{:genre=>"ダウンジャケット"},{:genre=>"ライダースジャケット"},{:genre=>"ミリタリージャケット"},{:genre=>"ダウンベスト"},{:genre=>"ジャンパー/ブルゾン"},{:genre=>"ポンチョ"},{:genre=>"ロングコート"},{:genre=>"トレンチコート"},{:genre=>"ダッフルコート"},{:genre=>"ピーコート"},{:genre=>"チェスターコート"},{:genre=>"モッズコート"},{:genre=>"スタジャン"},{:genre=>"毛皮/ファーコート"},{:genre=>"スプリングコート"},{:genre=>"スカジャン"},{:genre=>"その他"}])
lady_pants.children.create([{:genre=>"デニム/ジーンズ"},{:genre=>"ショートパンツ"},{:genre=>"カジュアルパンツ"},{:genre=>"ハーフパンツ"},{:genre=>"チノパン"},{:genre=>"ワークパンツ/カーゴパンツ"},{:genre=>"クロップドパンツ"},{:genre=>"サロペット/オーバーオール"},{:genre=>"オールインワン"},{:genre=>"サルエルパンツ"},{:genre=>"ガウチョパンツ"},{:genre=>"その他"}])
lady_skirt.children.create([{:genre=>"ミニスカート"},{:genre=>"ひざ丈スカート"},{:genre=>"ロングスカート"},{:genre=>"キュロット"},{:genre=>"その他"}])
lady_onepiece.children.create([{:genre=>"ミニワンピース"},{:genre=>"ひざ丈ワンピース"},{:genre=>"ロングワンピース"},{:genre=>"その他"}])
lady_shoes.children.create([{:genre=>"ハイヒール/パンプス"},{:genre=>"ブーツ"},{:genre=>"サンダル"},{:genre=>"スニーカー"},{:genre=>"ミュール"},{:genre=>"モカシン"},{:genre=>"ローファー/革靴"},{:genre=>"フラットシューズ/バレエシューズ"},{:genre=>"長靴/レインシューズ"},{:genre=>"その他"}])
lady_pajama.children.create([{:genre=>"パジャマ"},{:genre=>"ルームウェア"}])
lady_legwear.children.create([{:genre=>"ソックス"},{:genre=>"スパッツ/レギンス"},{:genre=>"ストッキング/タイツ"},{:genre=>"レッグウォーマー"},{:genre=>"その他"}])
lady_hat.children.create([{:genre=>"ニットキャップ/ビーニー"},{:genre=>"ハット"},{:genre=>"ハンチング/ベレー帽"},{:genre=>"キャップ"},{:genre=>"キャスケット"},{:genre=>"麦わら帽子"},{:genre=>"その他"}])
lady_bag.children.create([{:genre=>"ハンドバッグ"},{:genre=>"トートバッグ"},{:genre=>"エコバッグ"},{:genre=>"リュック/バックパック"},{:genre=>"ボストンバッグ"},{:genre=>"スポーツバッグ"},{:genre=>"ショルダーバッグ"},{:genre=>"クラッチバッグ"},{:genre=>"ポーチ/バニティ"},{:genre=>"ボディバッグ/ウェストバッグ"},{:genre=>"マザーズバッグ"},{:genre=>"メッセンジャーバッグ"},{:genre=>"ビジネスバッグ"},{:genre=>"旅行用バッグ/キャリーバッグ"},{:genre=>"ショップ袋"},{:genre=>"和装用バッグ"},{:genre=>"かごバッグ"},{:genre=>"その他"}])
lady_accessory.children.create([{:genre=>"ネックレス"},{:genre=>"ブレスレット"},{:genre=>"バングル/リストバンド"},{:genre=>"リング"},{:genre=>"ピアス(片耳用)"},{:genre=>"ピアス(両耳用)"},{:genre=>"イヤリング"},{:genre=>"アンクレット"},{:genre=>"ブローチ/コサージュ"},{:genre=>"チャーム"},{:genre=>"その他"}])
lady_hairacc.children.create([{:genre=>"ヘアゴム/シュシュ"},{:genre=>"ヘアバンド/カチューシャ"},{:genre=>"ヘアピン"},{:genre=>"その他"}])
lady_small.children.create([{:genre=>"長財布"},{:genre=>"折り財布"},{:genre=>"コインケース/小銭入れ"},{:genre=>"名刺入れ/定期入れ"},{:genre=>"キーケース"},{:genre=>"キーホルダー"},{:genre=>"手袋/アームカバー"},{:genre=>"ハンカチ"},{:genre=>"ベルト"},{:genre=>"マフラー/ショール"},{:genre=>"ストール/スヌード"},{:genre=>"バンダナ/スカーフ"},{:genre=>"ネックウォーマー"},{:genre=>"サスペンダー"},{:genre=>"サングラス/メガネ"},{:genre=>"モバイルケース/カバー"},{:genre=>"手帳"},{:genre=>"イヤマフラー"},{:genre=>"傘"},{:genre=>"レインコート/ポンチョ"},{:genre=>"ミラー"},{:genre=>"タバコグッズ"},{:genre=>"その他"}])
lady_watch.children.create([{:genre=>"腕時計(アナログ)"},{:genre=>"腕時計(デジタル)"},{:genre=>"ラバーベルト"},{:genre=>"レザーベルト"},{:genre=>"金属ベルト"},{:genre=>"その他"}])
lady_wig.children.create([{:genre=>"前髪ウィッグ"},{:genre=>"ロングストレート"},{:genre=>"ロングカール"},{:genre=>"ショートストレート"},{:genre=>"ショートカール"},{:genre=>"その他"}])
lady_yukata.children.create([{:genre=>"浴衣"},{:genre=>"着物"},{:genre=>"振袖"},{:genre=>"長襦袢/半襦袢"},{:genre=>"水着セパレート"},{:genre=>"水着ワンピース"},{:genre=>"水着スポーツ用"},{:genre=>"その他"}])
lady_suits.children.create([{:genre=>"スカートスーツ上下"},{:genre=>"パンツスーツ上下"},{:genre=>"ドレス"},{:genre=>"パーティーバッグ"},{:genre=>"シューズ"},{:genre=>"ウェディング"},{:genre=>"その他"}])
lady_maternity.children.create([{:genre=>"トップス"},{:genre=>"アウター"},{:genre=>"インナー"},{:genre=>"ワンピース"},{:genre=>"パンツ/スパッツ"},{:genre=>"スカート"},{:genre=>"パジャマ"},{:genre=>"授乳服"},{:genre=>"その他"}])
lady_others.children.create([{:genre=>"コスプレ"},{:genre=>"下着"},{:genre=>"その他"}])
men_tops.children.create([{:genre=>"Tシャツ/カットソー(半袖/袖なし)"},{:genre=>"Tシャツ/カットソー(七分/長袖)"},{:genre=>"シャツ"},{:genre=>"ポロシャツ"},{:genre=>"タンクトップ"},{:genre=>"ニット/セーター"},{:genre=>"パーカー"},{:genre=>"カーディガン"},{:genre=>"スウェット"},{:genre=>"ジャージ"},{:genre=>"ベスト"},{:genre=>"その他"}])
men_jacket.children.create([{:genre=>"テーラードジャケット"},{:genre=>"ノーカラージャケット"},{:genre=>"Gジャン/デニムジャケット"},{:genre=>"レザージャケット"},{:genre=>"ダウンジャケット"},{:genre=>"ライダースジャケット"},{:genre=>"ミリタリージャケット"},{:genre=>"ナイロンジャケット"},{:genre=>"フライトジャケット"},{:genre=>"ダッフルコート"},{:genre=>"ピーコート"},{:genre=>"ステンカラーコート"},{:genre=>"トレンチコート"},{:genre=>"モッズコート"},{:genre=>"チェスターコート"},{:genre=>"スタジャン"},{:genre=>"スカジャン"},{:genre=>"ブルゾン"},{:genre=>"マウンテンパーカー"},{:genre=>"ダウンベスト"},{:genre=>"ポンチョ"},{:genre=>"カバーオール"},{:genre=>"その他"}])
men_pants.children.create([{:genre=>"デニム/ジーンズ"},{:genre=>"ワークパンツ/カーゴパンツ"},{:genre=>"スラックス"},{:genre=>"チノパン"},{:genre=>"ショートパンツ"},{:genre=>"ペインターパンツ"},{:genre=>"サルエルパンツ"},{:genre=>"オーバーオール"},{:genre=>"その他"}])
men_shoes.children.create([{:genre=>"スニーカー"},{:genre=>"サンダル"},{:genre=>"ブーツ"},{:genre=>"モカシン"},{:genre=>"ドレス/ビジネス"},{:genre=>"長靴/レインシューズ"},{:genre=>"デッキシューズ"},{:genre=>"その他"}])
men_bag.children.create([{:genre=>"ショルダーバッグ"},{:genre=>"トートバッグ"},{:genre=>"ボストンバッグ"},{:genre=>"リュック/バックパック"},{:genre=>"ウエストポーチ"},{:genre=>"ボディーバッグ"},{:genre=>"ドラムバッグ"},{:genre=>"ビジネスバッグ"},{:genre=>"トラベルバッグ"},{:genre=>"メッセンジャーバッグ"},{:genre=>"エコバッグ"},{:genre=>"その他"}])
men_suits.children.create([{:genre=>"スーツジャケット"},{:genre=>"スーツベスト"},{:genre=>"スラックス"},{:genre=>"セットアップ"},{:genre=>"その他"}])
men_hat.children.create([{:genre=>"キャップ"},{:genre=>"ハット"},{:genre=>"ニットキャップ/ビーニー"},{:genre=>"ハンチング/ベレー帽"},{:genre=>"キャスケット"},{:genre=>"サンバイザー"},{:genre=>"その他"}])
men_accessory.children.create([{:genre=>"ネックレス"},{:genre=>"ブレスレット"},{:genre=>"バングル/リストバンド"},{:genre=>"リング"},{:genre=>"ピアス(片耳用)"},{:genre=>"ピアス(両耳用)"},{:genre=>"アンクレット"},{:genre=>"その他"}])
men_small.children.create([{:genre=>"長財布"},{:genre=>"折り財布"},{:genre=>"マネークリップ"},{:genre=>"コインケース/小銭入れ"},{:genre=>"名刺入れ/定期入れ"},{:genre=>"キーケース"},{:genre=>"キーホルダー"},{:genre=>"ネクタイ"},{:genre=>"手袋"},{:genre=>"ハンカチ"},{:genre=>"ベルト"},{:genre=>"マフラー"},{:genre=>"ストール"},{:genre=>"バンダナ"},{:genre=>"ネックウォーマー"},{:genre=>"サスペンダー"},{:genre=>"ウォレットチェーン"},{:genre=>"サングラス/メガネ"},{:genre=>"モバイルケース/カバー"},{:genre=>"手帳"},{:genre=>"ストラップ"},{:genre=>"ネクタイピン"},{:genre=>"カフリンクス"},{:genre=>"イヤマフラー"},{:genre=>"傘"},{:genre=>"レインコート"},{:genre=>"ミラー"},{:genre=>"タバコグッズ"},{:genre=>"その他"}])
men_watch.children.create([{:genre=>"腕時計(アナログ)"},{:genre=>"腕時計(デジタル)"},{:genre=>"ラバーベルト"},{:genre=>"レザーベルト"},{:genre=>"金属ベルト"},{:genre=>"その他"}])
men_swimsuits.children.create([{:genre=>"一般水着"},{:genre=>"スポーツ用"},{:genre=>"アクセサリー"},{:genre=>"その他"}])
men_legwear.children.create([{:genre=>"ソックス"},{:genre=>"レギンス/スパッツ"},{:genre=>"レッグウォーマー"},{:genre=>"その他"}])
men_underwear.children.create([{:genre=>"トランクス"},{:genre=>"ボクサーパンツ"},{:genre=>"その他"}])
men_others.children.create([{:genre=>"すべて"}])
kids_baby_girl.children.create([{:genre=>"トップス"},{:genre=>"アウター"},{:genre=>"パンツ"},{:genre=>"スカート"},{:genre=>"ワンピース"},{:genre=>"ベビードレス"},{:genre=>"おくるみ"},{:genre=>"下着/肌着"},{:genre=>"パジャマ"},{:genre=>"ロンパース"},{:genre=>"その他"}])
kids_baby_boy.children.create([{:genre=>"トップス"},{:genre=>"アウター"},{:genre=>"パンツ"},{:genre=>"おくるみ"},{:genre=>"下着/肌着"},{:genre=>"パジャマ"},{:genre=>"ロンパース"},{:genre=>"その他"}])
kids_baby_uni.children.create([{:genre=>"トップス"},{:genre=>"アウター"},{:genre=>"パンツ"},{:genre=>"おくるみ"},{:genre=>"下着/肌着"},{:genre=>"パジャマ"},{:genre=>"ロンパース"},{:genre=>"その他"}])
kids_girl.children.create([{:genre=>"コート"},{:genre=>"ジャケット/上着"},{:genre=>"トップス(Tシャツ/カットソー)"},{:genre=>"トップス(トレーナー)"},{:genre=>"トップス(チュニック)"},{:genre=>"トップス(タンクトップ)"},{:genre=>"トップス(その他)"},{:genre=>"スカート"},{:genre=>"パンツ"},{:genre=>"ワンピース"},{:genre=>"セットアップ"},{:genre=>"パジャマ"},{:genre=>"フォーマル/ドレス"},{:genre=>"和服"},{:genre=>"浴衣"},{:genre=>"甚平"},{:genre=>"水着"},{:genre=>"その他"}])
kids_boy.children.create([{:genre=>"コート"},{:genre=>"ジャケット/上着"},{:genre=>"トップス(Tシャツ/カットソー)"},{:genre=>"トップス(トレーナー)"},{:genre=>"トップス(その他)"},{:genre=>"パンツ"},{:genre=>"セットアップ"},{:genre=>"パジャマ"},{:genre=>"フォーマル/ドレス"},{:genre=>"和服"},{:genre=>"浴衣"},{:genre=>"甚平"},{:genre=>"水着"},{:genre=>"その他"}])
kids_uni.children.create([{:genre=>"コート"},{:genre=>"ジャケット/上着"},{:genre=>"トップス(Tシャツ/カットソー)"},{:genre=>"トップス(トレーナー)"},{:genre=>"トップス(その他)"},{:genre=>"ボトムス"},{:genre=>"パジャマ"},{:genre=>"その他"}])
kids_wear.children.create([{:genre=>"スニーカー"},{:genre=>"サンダル"},{:genre=>"ブーツ"},{:genre=>"長靴"},{:genre=>"その他"}])
kids_small.children.create([{:genre=>"靴下/スパッツ"},{:genre=>"帽子"},{:genre=>"エプロン"},{:genre=>"サスペンダー"},{:genre=>"タイツ"},{:genre=>"ハンカチ"},{:genre=>"バンダナ"},{:genre=>"ベルト"},{:genre=>"マフラー"},{:genre=>"傘"},{:genre=>"手袋"},{:genre=>"スタイ"},{:genre=>"バッグ"},{:genre=>"その他"}])
kids_bath.children.create([{:genre=>"おむつ用品"},{:genre=>"おまる/補助便座"},{:genre=>"トレーニングパンツ"},{:genre=>"ベビーバス"},{:genre=>"お風呂用品"},{:genre=>"その他"}])
kids_outside.children.create([{:genre=>"ベビーカー"},{:genre=>"抱っこひも/スリング"},{:genre=>"チャイルドシート"},{:genre=>"その他"}])
kids_meal.children.create([{:genre=>"ミルク"},{:genre=>"ベビーフード"},{:genre=>"ベビー用食器"},{:genre=>"その他"}])
kids_bed.children.create([{:genre=>"ベッド"},{:genre=>"布団/毛布"},{:genre=>"イス"},{:genre=>"たんす"},{:genre=>"その他"}])
kids_toy.children.create([{:genre=>"おふろのおもちゃ"},{:genre=>"がらがら"},{:genre=>"オルゴール"},{:genre=>"ベビージム"},{:genre=>"手押し車/カタカタ"},{:genre=>"知育玩具"},{:genre=>"その他"}])
kids_anni.children.create([{:genre=>"お宮参り用品"},{:genre=>"お食い初め用品"},{:genre=>"アルバム"},{:genre=>"手形/足形"},{:genre=>"その他"}])
kids_others.children.create([{:genre=>"母子手帳用品"},{:genre=>"その他"}])
houseware_kitchen.children.create([{:genre=>"食器"},{:genre=>"調理器具"},{:genre=>"収納/キッチン雑貨"},{:genre=>"弁当用品"},{:genre=>"カトラリー(スプーン等)"},{:genre=>"テーブル用品"},{:genre=>"容器"},{:genre=>"エプロン"},{:genre=>"アルコールグッズ"},{:genre=>"浄水機"},{:genre=>"その他"}])
houseware_bed.children.create([{:genre=>"セミシングルベッド"},{:genre=>"シングルベッド"},{:genre=>"セミダブルベッド"},{:genre=>"ダブルベッド"},{:genre=>"ワイドダブルベッド"},{:genre=>"クイーンベッド"},{:genre=>"キングベッド"},{:genre=>"脚付きマットレスベッド"},{:genre=>"マットレス"},{:genre=>"すのこベッド"},{:genre=>"ロフトベッド/システムベッド"},{:genre=>"簡易ベッド/折りたたみベッド"},{:genre=>"収納付き"},{:genre=>"その他"}])
houseware_sofa.children.create([{:genre=>"ソファセット"},{:genre=>"シングルソファ"},{:genre=>"ラブソファ"},{:genre=>"トリプルソファ"},{:genre=>"オットマン"},{:genre=>"コーナーソファ"},{:genre=>"ビーズソファ/クッションソファ"},{:genre=>"ローソファ/フロアソファ"},{:genre=>"ソファベッド"},{:genre=>"応接セット"},{:genre=>"ソファカバー"},{:genre=>"リクライニングソファ"},{:genre=>"その他"}])
houseware_chair.children.create([{:genre=>"一般"},{:genre=>"スツール"},{:genre=>"ダイニングチェア"},{:genre=>"ハイバックチェア"},{:genre=>"ロッキングチェア"},{:genre=>"座椅子"},{:genre=>"折り畳みイス"},{:genre=>"デスクチェア"},{:genre=>"その他"}])
houseware_table.children.create([{:genre=>"こたつ"},{:genre=>"カウンターテーブル"},{:genre=>"サイドテーブル"},{:genre=>"センターテーブル"},{:genre=>"ダイニングテーブル"},{:genre=>"座卓/ちゃぶ台"},{:genre=>"アウトドア用"},{:genre=>"パソコン用"},{:genre=>"事務机/学習机"},{:genre=>"その他"}])
houseware_storage.children.create([{:genre=>"リビング収納"},{:genre=>"キッチン収納"},{:genre=>"玄関/屋外収納"},{:genre=>"バス/トイレ収納"},{:genre=>"本収納"},{:genre=>"本/CD/DVD収納"},{:genre=>"洋服タンス/押入れ収納"},{:genre=>"電話台/ファックス台"},{:genre=>"ドレッサー/鏡台"},{:genre=>"棚/ラック"},{:genre=>"ケース/ボックス"},{:genre=>"その他"}])
houseware_carpet.children.create([{:genre=>"ラグ"},{:genre=>"カーペット"},{:genre=>"ホットカーペット"},{:genre=>"玄関/キッチンマット"},{:genre=>"トイレ/バスマット"},{:genre=>"その他"}])
houseware_curtain.children.create([{:genre=>"カーテン"},{:genre=>"ブラインド"},{:genre=>"ロールスクリーン"},{:genre=>"のれん"},{:genre=>"その他"}])
houseware_light.children.create([{:genre=>"蛍光灯/電球"},{:genre=>"天井照明"},{:genre=>"フロアスタンド"},{:genre=>"その他"}])
houseware_bedding.children.create([{:genre=>"布団/毛布"},{:genre=>"枕"},{:genre=>"シーツ/カバー"},{:genre=>"その他"}])
houseware_interior.children.create([{:genre=>"ごみ箱"},{:genre=>"ウェルカムボード"},{:genre=>"オルゴール"},{:genre=>"クッション"},{:genre=>"クッションカバー"},{:genre=>"スリッパラック"},{:genre=>"ティッシュボックス"},{:genre=>"バスケット/かご"},{:genre=>"フォトフレーム"},{:genre=>"マガジンラック"},{:genre=>"モビール"},{:genre=>"花瓶"},{:genre=>"灰皿"},{:genre=>"傘立て"},{:genre=>"小物入れ"},{:genre=>"置時計"},{:genre=>"掛時計/柱時計"},{:genre=>"鏡(立て掛け式)"},{:genre=>"鏡(壁掛け式)"},{:genre=>"置物"},{:genre=>"風鈴"},{:genre=>"植物/観葉植物"},{:genre=>"その他"}])
houseware_seasonal.children.create([{:genre=>"正月"},{:genre=>"成人式"},{:genre=>"バレンタインデー"},{:genre=>"ひな祭り"},{:genre=>"子どもの日"},{:genre=>"母の日"},{:genre=>"父の日"},{:genre=>"サマーギフト/お中元"},{:genre=>"夏/夏休み"},{:genre=>"ハロウィン"},{:genre=>"敬老の日"},{:genre=>"七五三"},{:genre=>"お歳暮"},{:genre=>"クリスマス"},{:genre=>"冬一般"},{:genre=>"その他"}])
houseware_others.children.create([{:genre=>"すべて"}])
entertainment_book.children.create([{:genre=>"文学/小説"},{:genre=>"人文/社会"},{:genre=>"ノンフィクション/教養"},{:genre=>"地図/旅行ガイド"},{:genre=>"ビジネス/経済"},{:genre=>"健康/医学"},{:genre=>"コンピュータ/IT"},{:genre=>"趣味/スポーツ/実用"},{:genre=>"住まい/暮らし/子育て"},{:genre=>"アート/エンタメ"},{:genre=>"洋書"},{:genre=>"絵本"},{:genre=>"参考書"},{:genre=>"その他"}])
entertainment_comic.children.create([{:genre=>"全巻セット"},{:genre=>"少年漫画"},{:genre=>"少女漫画"},{:genre=>"青年漫画"},{:genre=>"女性漫画"},{:genre=>"同人誌"},{:genre=>"その他"}])
entertainment_magazine.children.create([{:genre=>"アート/エンタメ/ホビー"},{:genre=>"ファッション"},{:genre=>"ニュース/総合"},{:genre=>"趣味/スポーツ"},{:genre=>"その他"}])
entertainment_cd.children.create([{:genre=>"邦楽"},{:genre=>"洋楽"},{:genre=>"アニメ"},{:genre=>"クラシック"},{:genre=>"K-POP/アジア"},{:genre=>"キッズ/ファミリー"},{:genre=>"その他"}])
entertainment_dvd.children.create([{:genre=>"外国映画"},{:genre=>"日本映画"},{:genre=>"アニメ"},{:genre=>"TVドラマ"},{:genre=>"ミュージック"},{:genre=>"お笑い/バラエティ"},{:genre=>"スポーツ/フィットネス"},{:genre=>"キッズ/ファミリー"},{:genre=>"その他"}])
entertainment_record.children.create([{:genre=>"邦楽"},{:genre=>"洋楽"},{:genre=>"その他"}])
entertainment_game.children.create([{:genre=>"家庭用ゲーム本体"},{:genre=>"家庭用ゲームソフト"},{:genre=>"携帯用ゲーム本体"},{:genre=>"携帯用ゲームソフト"},{:genre=>"PCゲーム"},{:genre=>"その他"}])
hobby_toy.children.create([{:genre=>"キャラクターグッズ"},{:genre=>"ぬいぐるみ"},{:genre=>"小物/アクセサリー"},{:genre=>"模型/プラモデル"},{:genre=>"ミニカー"},{:genre=>"トイラジコン"},{:genre=>"プラモデル"},{:genre=>"ホビーラジコン"},{:genre=>"鉄道模型"},{:genre=>"その他"}])
hobby_talent.children.create([{:genre=>"アイドル"},{:genre=>"ミュージシャン"},{:genre=>"タレント/お笑い芸人"},{:genre=>"スポーツ選手"},{:genre=>"その他"}])
hobby_comic_goods.children.create([{:genre=>"ストラップ"},{:genre=>"キーホルダー"},{:genre=>"バッジ"},{:genre=>"カード"},{:genre=>"クリアファイル"},{:genre=>"ポスター"},{:genre=>"タオル"},{:genre=>"その他"}])
hobby_cards.children.create([{:genre=>"遊戯王"},{:genre=>"マジック：ザ・ギャザリング"},{:genre=>"ポケモンカードゲーム"},{:genre=>"デュエルマスターズ"},{:genre=>"バトルスピリッツ"},{:genre=>"プリパラ"},{:genre=>"アイカツ"},{:genre=>"カードファイト!! ヴァンガード"},{:genre=>"ヴァイスシュヴァルツ"},{:genre=>"プロ野球オーナーズリーグ"},{:genre=>"ベースボールヒーローズ"},{:genre=>"ドラゴンボール"},{:genre=>"スリーブ"},{:genre=>"その他"}])
hobby_figure.children.create([{:genre=>"コミック/アニメ"},{:genre=>"特撮"},{:genre=>"ゲームキャラクター"},{:genre=>"SF/ファンタジー/ホラー"},{:genre=>"アメコミ"},{:genre=>"スポーツ"},{:genre=>"ミリタリー"},{:genre=>"その他"}])
hobby_instrument.children.create([{:genre=>"エレキギター"},{:genre=>"アコースティックギター"},{:genre=>"ベース"},{:genre=>"エフェクター"},{:genre=>"アンプ"},{:genre=>"弦楽器"},{:genre=>"管楽器"},{:genre=>"鍵盤楽器"},{:genre=>"打楽器"},{:genre=>"和楽器"},{:genre=>"楽譜/スコア"},{:genre=>"レコーディング/PA機器"},{:genre=>"DJ機器"},{:genre=>"DTM/DAW"},{:genre=>"その他"}])
hobby_collection.children.create([{:genre=>"武具"},{:genre=>"使用済切手/官製はがき"},{:genre=>"旧貨幣/金貨/銀貨/記念硬貨"},{:genre=>"印刷物"},{:genre=>"ノベルティグッズ"},{:genre=>"その他"}])
hobby_military.children.create([{:genre=>"トイガン"},{:genre=>"個人装備"},{:genre=>"その他"}])
hobby_picture.children.create([{:genre=>"陶芸"},{:genre=>"ガラス"},{:genre=>"漆芸"},{:genre=>"金属工芸"},{:genre=>"絵画/タペストリ"},{:genre=>"版画"},{:genre=>"彫刻/オブジェクト"},{:genre=>"書"},{:genre=>"写真"},{:genre=>"その他"}])
hobby_art.children.create([{:genre=>"画材"},{:genre=>"額縁"},{:genre=>"その他"}])
hobby_others.children.create([{:genre=>"トランプ/UNO"},{:genre=>"カルタ/百人一首"},{:genre=>"ダーツ"},{:genre=>"ビリヤード"},{:genre=>"麻雀"},{:genre=>"パズル/ジグソーパズル"},{:genre=>"囲碁/将棋"},{:genre=>"オセロ/チェス"},{:genre=>"人生ゲーム"},{:genre=>"野球/サッカーゲーム"},{:genre=>"スポーツ"},{:genre=>"三輪車/乗り物"},{:genre=>"ヨーヨー"},{:genre=>"模型製作用品"},{:genre=>"鉄道"},{:genre=>"航空機"},{:genre=>"アマチュア無線"},{:genre=>"パチンコ/パチスロ"},{:genre=>"その他"}])
cosme_base.children.create([{:genre=>"ファンデーション"},{:genre=>"化粧下地"},{:genre=>"コントロールカラー"},{:genre=>"BBクリーム"},{:genre=>"CCクリーム"},{:genre=>"コンシーラー"},{:genre=>"フェイスパウダー"},{:genre=>"トライアルセット/サンプル"},{:genre=>"その他"}])
cosme_makeup.children.create([{:genre=>"アイシャドウ"},{:genre=>"口紅"},{:genre=>"リップグロス"},{:genre=>"リップライナー"},{:genre=>"チーク"},{:genre=>"フェイスカラー"},{:genre=>"マスカラ"},{:genre=>"アイライナー"},{:genre=>"つけまつげ"},{:genre=>"アイブロウペンシル"},{:genre=>"パウダーアイブロウ"},{:genre=>"眉マスカラ"},{:genre=>"トライアルセット/サンプル"},{:genre=>"メイク道具/化粧小物"},{:genre=>"美顔用品/美顔ローラー"},{:genre=>"その他"}])
cosme_nail.children.create([{:genre=>"ネイルカラー"},{:genre=>"カラージェル"},{:genre=>"ネイルベースコート/トップコート"},{:genre=>"ネイルアート用品"},{:genre=>"ネイルパーツ"},{:genre=>"ネイルチップ/付け爪"},{:genre=>"手入れ用具"},{:genre=>"除光液"},{:genre=>"その他"}])
cosme_perfume.children.create([{:genre=>"香水(女性用)"},{:genre=>"香水(男性用)"},{:genre=>"ユニセックス"},{:genre=>"ボディミスト"},{:genre=>"その他"}])
cosme_skincare.children.create([{:genre=>"化粧水/ローション"},{:genre=>"乳液/ミルク"},{:genre=>"美容液"},{:genre=>"フェイスクリーム"},{:genre=>"洗顔料"},{:genre=>"クレンジング/メイク落とし"},{:genre=>"パック/フェイスマスク"},{:genre=>"ジェル/ゲル"},{:genre=>"ブースター/導入液"},{:genre=>"アイケア"},{:genre=>"リップケア"},{:genre=>"トライアルセット/サンプル"},{:genre=>"洗顔グッズ"},{:genre=>"その他"}])
cosme_haircare.children.create([{:genre=>"シャンプー"},{:genre=>"トリートメント"},{:genre=>"コンディショナー"},{:genre=>"リンス"},{:genre=>"スタイリング剤"},{:genre=>"カラーリング剤"},{:genre=>"ブラシ"},{:genre=>"その他"}])
cosme_bodycare.children.create([{:genre=>"オイル/クリーム"},{:genre=>"ハンドクリーム"},{:genre=>"ローション"},{:genre=>"日焼け止め/サンオイル"},{:genre=>"ボディソープ"},{:genre=>"入浴剤"},{:genre=>"制汗/デオドラント"},{:genre=>"フットケア"},{:genre=>"その他"}])
cosme_oralcare.children.create([{:genre=>"口臭防止/エチケット用品"},{:genre=>"歯ブラシ"},{:genre=>"その他"}])
cosme_relax.children.create([{:genre=>"エッセンシャルオイル"},{:genre=>"芳香器"},{:genre=>"お香/香炉"},{:genre=>"キャンドル"},{:genre=>"リラクゼーショングッズ"},{:genre=>"その他"}])
cosme_diet.children.create([{:genre=>"ダイエット食品"},{:genre=>"エクササイズ用品"},{:genre=>"体重計"},{:genre=>"体脂肪計"},{:genre=>"その他"}])
cosme_others.children.create([{:genre=>"健康用品"},{:genre=>"看護/介護用品"},{:genre=>"救急/衛生用品"},{:genre=>"その他"}])
electric_phone.children.create([{:genre=>"スマートフォン本体"},{:genre=>"バッテリー/充電器"},{:genre=>"携帯電話本体"},{:genre=>"PHS本体"},{:genre=>"その他"}])
electric_accessory.children.create([{:genre=>"Android用ケース"},{:genre=>"iPhone用ケース"},{:genre=>"カバー"},{:genre=>"イヤホンジャック"},{:genre=>"ストラップ"},{:genre=>"フィルム"},{:genre=>"自撮り棒"},{:genre=>"その他"}])
electric_pc.children.create([{:genre=>"タブレット"},{:genre=>"ノートPC"},{:genre=>"デスクトップ型PC"},{:genre=>"ディスプレイ"},{:genre=>"電子ブックリーダー"},{:genre=>"PC周辺機器"},{:genre=>"PCパーツ"},{:genre=>"その他"}])
electric_camera.children.create([{:genre=>"デジタルカメラ"},{:genre=>"ビデオカメラ"},{:genre=>"レンズ(単焦点)"},{:genre=>"レンズ(ズーム)"},{:genre=>"フィルムカメラ"},{:genre=>"防犯カメラ"},{:genre=>"その他"}])
electric_tv.children.create([{:genre=>"テレビ"},{:genre=>"プロジェクター"},{:genre=>"ブルーレイレコーダー"},{:genre=>"DVDレコーダー"},{:genre=>"ブルーレイプレーヤー"},{:genre=>"DVDプレーヤー"},{:genre=>"映像用ケーブル"},{:genre=>"その他"}])
electric_audio.children.create([{:genre=>"ポータブルプレーヤー"},{:genre=>"イヤフォン"},{:genre=>"ヘッドフォン"},{:genre=>"アンプ"},{:genre=>"スピーカー"},{:genre=>"ケーブル/シールド"},{:genre=>"ラジオ"},{:genre=>"その他"}])
electric_beauty.children.create([{:genre=>"ヘアドライヤー"},{:genre=>"ヘアアイロン"},{:genre=>"美容機器"},{:genre=>"電気シェーバー"},{:genre=>"電動歯ブラシ"},{:genre=>"その他"}])
electric_aircon.children.create([{:genre=>"エアコン"},{:genre=>"空気清浄器"},{:genre=>"加湿器"},{:genre=>"扇風機"},{:genre=>"除湿機"},{:genre=>"ファンヒーター "},{:genre=>"電気ヒーター"},{:genre=>"オイルヒーター"},{:genre=>"ストーブ"},{:genre=>"ホットカーペット"},{:genre=>"こたつ"},{:genre=>"電気毛布"},{:genre=>"その他"}])
electric_appliance.children.create([{:genre=>"冷蔵庫"},{:genre=>"洗濯機"},{:genre=>"炊飯器"},{:genre=>"電子レンジ/オーブン"},{:genre=>"調理機器"},{:genre=>"アイロン"},{:genre=>"掃除機"},{:genre=>"エスプレッソマシン"},{:genre=>"コーヒーメーカー"},{:genre=>"衣類乾燥機"},{:genre=>"その他"}])
electric_others.children.create([{:genre=>"その他"}])
sports_golf.children.create([{:genre=>"クラブ"},{:genre=>"ウエア(男性用)"},{:genre=>"ウエア(女性用)"},{:genre=>"バッグ "},{:genre=>"シューズ(男性用)"},{:genre=>"シューズ(女性用)"},{:genre=>"アクセサリー"},{:genre=>"その他"}])
sports_fishing.children.create([{:genre=>"ロッド"},{:genre=>"リール"},{:genre=>"ルアー用品"},{:genre=>"ウエア"},{:genre=>"釣り糸/ライン"},{:genre=>"その他"}])
sports_bike.children.create([{:genre=>"自転車本体"},{:genre=>"ウエア"},{:genre=>"パーツ"},{:genre=>"アクセサリー"},{:genre=>"バッグ"},{:genre=>"工具/メンテナンス"},{:genre=>"その他"}])
sports_exercise.children.create([{:genre=>"ランニング"},{:genre=>"ウォーキング"},{:genre=>"ヨガ"},{:genre=>"トレーニング用品"},{:genre=>"その他"}])
sports_baseball.children.create([{:genre=>"ウェア"},{:genre=>"シューズ"},{:genre=>"グローブ"},{:genre=>"バット"},{:genre=>"アクセサリー"},{:genre=>"防具"},{:genre=>"練習機器"},{:genre=>"記念グッズ"},{:genre=>"応援グッズ"},{:genre=>"その他"}])
sports_soccer.children.create([{:genre=>"ウェア"},{:genre=>"シューズ"},{:genre=>"ボール"},{:genre=>"アクセサリー"},{:genre=>"記念グッズ"},{:genre=>"応援グッズ"},{:genre=>"その他"}])
sports_tennis.children.create([{:genre=>"ラケット(硬式用)"},{:genre=>"ラケット(軟式用)"},{:genre=>"ウェア"},{:genre=>"シューズ"},{:genre=>"ボール"},{:genre=>"アクセサリー"},{:genre=>"記念グッズ"},{:genre=>"応援グッズ"},{:genre=>"その他"}])
sports_snowboard.children.create([{:genre=>"ボード"},{:genre=>"バインディング"},{:genre=>"ブーツ(男性用)"},{:genre=>"ブーツ(女性用)"},{:genre=>"ブーツ(子ども用)"},{:genre=>"ウエア/装備(男性用)"},{:genre=>"ウエア/装備(女性用)"},{:genre=>"ウエア/装備(子ども用)"},{:genre=>"アクセサリー"},{:genre=>"バッグ"},{:genre=>"その他"}])
sports_ski.children.create([{:genre=>"板"},{:genre=>"ブーツ(男性用)"},{:genre=>"ブーツ(女性用)"},{:genre=>"ブーツ(子ども用)"},{:genre=>"ビンディング"},{:genre=>"ウエア(男性用)"},{:genre=>"ウエア(女性用)"},{:genre=>"ウエア(子ども用)"},{:genre=>"ストック"},{:genre=>"その他"}])
sports_other_sports.children.create([{:genre=>"ダンス/バレエ"},{:genre=>"サーフィン"},{:genre=>"バスケットボール"},{:genre=>"バドミントン"},{:genre=>"バレーボール"},{:genre=>"スケートボード"},{:genre=>"陸上競技"},{:genre=>"ラグビー"},{:genre=>"アメリカンフットボール"},{:genre=>"ボクシング"},{:genre=>"ボウリング"},{:genre=>"その他"}])
sports_outdoor.children.create([{:genre=>"テント/タープ"},{:genre=>"ライト/ランタン"},{:genre=>"寝袋/寝具"},{:genre=>"テーブル/チェア"},{:genre=>"ストーブ/コンロ"},{:genre=>"調理器具"},{:genre=>"食器"},{:genre=>"登山用品"},{:genre=>"その他"}])
sports_others.children.create([{:genre=>"旅行用品"},{:genre=>"その他"}])
handmade_accessory.children.create([{:genre=>"ピアス"},{:genre=>"イヤリング"},{:genre=>"ネックレス"},{:genre=>"ブレスレット"},{:genre=>"リング"},{:genre=>"チャーム"},{:genre=>"ヘアゴム"},{:genre=>"アンクレット"},{:genre=>"その他"}])
handmade_small.children.create([{:genre=>"バッグ(女性用)"},{:genre=>"バッグ(男性用)"},{:genre=>"財布(女性用)"},{:genre=>"財布(男性用)"},{:genre=>"ファッション雑貨"},{:genre=>"その他"}])
handmade_watch.children.create([{:genre=>"アクセサリー(男性用)"},{:genre=>"時計(女性用)"},{:genre=>"時計(男性用)"},{:genre=>"その他"}])
handmade_interior.children.create([{:genre=>"キッチン用品"},{:genre=>"家具"},{:genre=>"文房具"},{:genre=>"アート/写真"},{:genre=>"アロマ/キャンドル"},{:genre=>"フラワー/ガーデン"},{:genre=>"その他"}])
handmade_hobby.children.create([{:genre=>"クラフト/布製品"},{:genre=>"おもちゃ/人形"},{:genre=>"その他"}])
handmade_kids.children.create([{:genre=>"ファッション雑貨"},{:genre=>"スタイ/よだれかけ"},{:genre=>"外出用品"},{:genre=>"ネームタグ"},{:genre=>"その他"}])
handmade_material.children.create([{:genre=>"各種パーツ"},{:genre=>"生地/糸"},{:genre=>"型紙/パターン"},{:genre=>"その他"}])
handmade_fanmade.children.create([{:genre=>"Ingress"},{:genre=>"クリエイターズ宇宙兄弟"}])
handmade_others.children.create([{:genre=>"その他"}])
ticket_music.children.create([{:genre=>"男性アイドル"},{:genre=>"女性アイドル"},{:genre=>"韓流"},{:genre=>"国内アーティスト"},{:genre=>"海外アーティスト"},{:genre=>"音楽フェス"},{:genre=>"声優/アニメ"},{:genre=>"その他"}])
ticket_sports.children.create([{:genre=>"サッカー"},{:genre=>"野球"},{:genre=>"テニス"},{:genre=>"格闘技/プロレス"},{:genre=>"相撲/武道"},{:genre=>"ゴルフ"},{:genre=>"バレーボール"},{:genre=>"バスケットボール"},{:genre=>"モータースポーツ"},{:genre=>"ウィンタースポーツ"},{:genre=>"その他"}])
ticket_entertainment.children.create([{:genre=>"ミュージカル"},{:genre=>"演劇"},{:genre=>"伝統芸能"},{:genre=>"落語"},{:genre=>"お笑い"},{:genre=>"オペラ"},{:genre=>"サーカス"},{:genre=>"バレエ"},{:genre=>"その他"}])
ticket_event.children.create([{:genre=>"声優/アニメ"},{:genre=>"キッズ/ファミリー"},{:genre=>"トークショー/講演会"},{:genre=>"その他"}])
ticket_movie.children.create([{:genre=>"邦画"},{:genre=>"洋画"},{:genre=>"その他"}])
ticket_facility.children.create([{:genre=>"遊園地/テーマパーク"},{:genre=>"美術館/博物館"},{:genre=>"スキー場"},{:genre=>"ゴルフ場"},{:genre=>"フィットネスクラブ"},{:genre=>"プール"},{:genre=>"ボウリング場"},{:genre=>"水族館"},{:genre=>"動物園"},{:genre=>"その他"}])
ticket_voucher.children.create([{:genre=>"ショッピング"},{:genre=>"レストラン/食事券"},{:genre=>"フード/ドリンク券"},{:genre=>"宿泊券"},{:genre=>"その他"}])
ticket_otehrs.children.create([{:genre=>"その他"}])
behicle_car.children.create([{:genre=>"国内自動車本体"},{:genre=>"外国自動車本体"}])
behicle_wheel.children.create([{:genre=>"タイヤ/ホイールセット"},{:genre=>"タイヤ"},{:genre=>"ホイール"},{:genre=>"その他"}])
behicle_part.children.create([{:genre=>"サスペンション"},{:genre=>"ブレーキ"},{:genre=>"外装、エアロパーツ"},{:genre=>"ライト"},{:genre=>"内装品、シート"},{:genre=>"ステアリング"},{:genre=>"マフラー・排気系"},{:genre=>"エンジン、過給器、冷却装置"},{:genre=>"クラッチ、ミッション、駆動系"},{:genre=>"電装品"},{:genre=>"補強パーツ"},{:genre=>"汎用パーツ"},{:genre=>"外国自動車用パーツ"},{:genre=>"その他"}])
behicle_accessory.children.create([{:genre=>"車内アクセサリー"},{:genre=>"カーナビ"},{:genre=>"カーオーディオ"},{:genre=>"車外アクセサリー"},{:genre=>"メンテナンス用品"},{:genre=>"チャイルドシート"},{:genre=>"ドライブレコーダー"},{:genre=>"レーダー探知機"},{:genre=>"カタログ/マニュアル"},{:genre=>"セキュリティ"},{:genre=>"ETC"},{:genre=>"その他"}])
behicle_autobike.children.create([{:genre=>"すべて"}])
behicle_bike_part.children.create([{:genre=>"タイヤ"},{:genre=>"マフラー"},{:genre=>"エンジン、冷却装置"},{:genre=>"カウル、フェンダー、外装"},{:genre=>"サスペンション"},{:genre=>"ホイール"},{:genre=>"シート"},{:genre=>"ブレーキ"},{:genre=>"タンク"},{:genre=>"ライト、ウィンカー"},{:genre=>"チェーン、スプロケット、駆動系"},{:genre=>"メーター"},{:genre=>"電装系"},{:genre=>"ミラー"},{:genre=>"外国オートバイ用パーツ"},{:genre=>"その他"}])
behicle_bike_accessory.children.create([{:genre=>"ヘルメット/シールド"},{:genre=>"バイクウエア/装備"},{:genre=>"アクセサリー"},{:genre=>"メンテナンス"},{:genre=>"カタログ/マニュアル"},{:genre=>"その他"}])
others_bigshop.children.create([{:genre=>"すべて"}])
others_pet.children.create([{:genre=>"ペットフード"},{:genre=>"犬用品"},{:genre=>"猫用品"},{:genre=>"魚用品/水草"},{:genre=>"小動物用品"},{:genre=>"爬虫類/両生類用品"},{:genre=>"かご/おり"},{:genre=>"鳥用品"},{:genre=>"虫類用品"},{:genre=>"その他"}])
others_food.children.create([{:genre=>"菓子"},{:genre=>"米"},{:genre=>"野菜"},{:genre=>"果物"},{:genre=>"調味料"},{:genre=>"魚介類(加工食品)"},{:genre=>"肉類(加工食品)"},{:genre=>"その他 加工食品"},{:genre=>"その他"}])
others_bevarage.children.create([{:genre=>"コーヒー"},{:genre=>"ソフトドリンク"},{:genre=>"ミネラルウォーター"},{:genre=>"茶"},{:genre=>"ウイスキー"},{:genre=>"ワイン"},{:genre=>"ブランデー"},{:genre=>"焼酎"},{:genre=>"日本酒"},{:genre=>"ビール、発泡酒"},{:genre=>"その他"}])
others_grocery.children.create([{:genre=>"タオル/バス用品"},{:genre=>"日用品/生活雑貨"},{:genre=>"洗剤/柔軟剤"},{:genre=>"旅行用品"},{:genre=>"防災関連グッズ"},{:genre=>"その他"}])
others_antique.children.create([{:genre=>"雑貨"},{:genre=>"工芸品"},{:genre=>"家具"},{:genre=>"印刷物"},{:genre=>"その他"}])
others_stationary.children.create([{:genre=>"筆記具"},{:genre=>"ノート/メモ帳"},{:genre=>"テープ/マスキングテープ"},{:genre=>"カレンダー/スケジュール"},{:genre=>"アルバム/スクラップ"},{:genre=>"ファイル/バインダー"},{:genre=>"はさみ/カッター"},{:genre=>"カードホルダー/名刺管理"},{:genre=>"のり/ホッチキス"},{:genre=>"その他"}])
others_shop.children.create([{:genre=>"オフィス用品一般"},{:genre=>"オフィス家具"},{:genre=>"店舗用品"},{:genre=>"OA機器"},{:genre=>"ラッピング/包装"},{:genre=>"その他"}])
others_others.children.create([{:genre=>"すべて"}])